source "https://rubygems.org"

gem "fastlane"

# iOS-specific plugins
gem "fastlane-plugin-firebase_app_distribution"
gem "cocoapods"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
